#if !canImport(ObjectiveC)
import XCTest

extension AssertFailureTestCaseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AssertFailureTestCaseTests = [
        ("testEmptyTest", testEmptyTest),
        ("testExactNumberOfRepetitionIsRequired", testExactNumberOfRepetitionIsRequired),
        ("testExpectedAnyFailure", testExpectedAnyFailure),
        ("testExpectedFailure", testExpectedFailure),
        ("testExpectedFailureCanBeRepeated", testExpectedFailureCanBeRepeated),
        ("testExpectedFailureMatchesOnPrefix", testExpectedFailureMatchesOnPrefix),
        ("testMissedFailure", testMissedFailure),
        ("testMissingAnyFailure", testMissingAnyFailure),
        ("testOrderOfExpectedFailureIsIgnored", testOrderOfExpectedFailureIsIgnored),
        ("testUnexpectedFailure", testUnexpectedFailure),
    ]
}

extension CombineSpyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CombineSpyTests = [
        ("testElements", testElements),
        ("testNext", testNext),
        ("testSpySubscribes", testSpySubscribes),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AssertFailureTestCaseTests.__allTests__AssertFailureTestCaseTests),
        testCase(CombineSpyTests.__allTests__CombineSpyTests),
    ]
}
#endif
